name: dinov2-extras
channels:
# Remove defaults channel due to Anaconda TOS
#  - defaults
  - pytorch
  - nvidia
  - xformers
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  # - pytorch::pytorch=2.0.0
  # - pytorch::pytorch-cuda=11.7.0
  # - pytorch::torchvision=0.15.0
  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - xformers::xformers=0.0.18
  - pip
  # - pip:
  #   - --extra-index-url https://download.pytorch.org/whl/cu117
  #   - torch==2.0.0+cu117
  #   - torchvision==0.15.0
  #   - git+https://github.com/facebookincubator/submitit
  #   - --extra-index-url https://pypi.nvidia.com
  #   - cuml-cu11
  #   - mmcv-full==1.5.0
  #   - mmsegmentation==0.27.0
  
# Manually install the following:
# pip install torch==2.0.0+cu117 torchvision==0.15.0 --extra-index-url https://download.pytorch.org/whl/cu117

# And then:
# pip install \
#   git+https://github.com/facebookincubator/submitit \
#   cuml-cu11 \
#   mmcv-full==1.5.0 \
#   mmsegmentation==0.27.0 \
#   --extra-index-url https://pypi.nvidia.com
    
