dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 192
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 16
  dataset_path: ImageNet:split=TRAIN:root=/Users/AlfredAqraouXPS15/Desktop/DTU/Year 2/Semester 4/02466 Project work - Bsc of AI and data/02466-Project/dataset/fluorescent/without_masks_224
  centering: sinkhorn_knopp
student:
  arch: vit_small
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 300
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 80
  layerwise_decay: 1.0
crops:
  local_crops_size: 98